# Generated by Django 5.1.4 on 2025-01-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='is_delete',
            field=models.BooleanField(default=False, verbose_name='حذف شده/حذف نشده'),
        ),
    ]
