# Generated by Django 5.1.4 on 2025-02-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_module', '0003_productbrand_alter_product_price_alter_product_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.CharField(blank=True, default='', max_length=200, unique=True, verbose_name='عنوان در Url'),
        ),
    ]
